// frontend/pages/stock/index.vue
<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
          <UIcon name="i-heroicons-chart-bar" class="w-7 h-7 text-emerald-400" />
          Thị trường cổ phiếu Việt Nam
        </h1>
        <p class="text-xs sm:text-sm text-slate-400 mt-1">
          Dữ liệu niêm yết HOSE, HNX, UPCOM đồng bộ từ vnstock — Tổng số: <span class="font-mono text-emerald-400 font-semibold">{{ total }}</span> mã
        </p>
      </div>

      <UButton
        color="gray"
        variant="solid"
        size="sm"
        :loading="isLoading"
        class="self-start sm:self-auto"
        @click="loadSymbols"
      >
        <template #leading>
          <UIcon name="i-heroicons-arrow-path" :class="{ 'animate-spin': isLoading }" class="w-4 h-4" />
        </template>
        Làm mới
      </UButton>
    </div>

    <!-- Filter Bar -->
    <div class="flex flex-col sm:flex-row gap-3">
      <div class="relative flex-1 max-w-md">
        <UInput
          v-model="search"
          placeholder="Tìm theo mã CK hoặc tên công ty..."
          icon="i-heroicons-magnifying-glass"
          size="md"
          class="w-full"
          @input="onSearchChange"
        />
      </div>

      <USelectMenu
        v-model="selectedExchange"
        :options="exchangeOptions"
        value-attribute="value"
        option-attribute="label"
        class="w-44"
        size="md"
        placeholder="Chọn sàn"
        @change="onExchangeChange"
      />
    </div>

    <!-- Stock Symbols Table Card -->
    <div class="rounded-xl border border-slate-800 bg-slate-900/60 overflow-hidden shadow-xl">
      <div class="p-4 border-b border-slate-800/80 flex items-center justify-between">
        <span class="text-xs font-semibold text-slate-300 uppercase tracking-wider">
          Bảng mã niêm yết
        </span>
        <span class="text-xs text-slate-400">
          Hiển thị trang {{ page + 1 }} / {{ maxPages || 1 }}
        </span>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full text-left text-xs">
          <thead class="bg-slate-900/90 text-slate-400 uppercase font-mono text-[11px] border-b border-slate-800">
            <tr>
              <th class="py-3 px-4 w-28">Mã CK</th>
              <th class="py-3 px-4">Tên công ty</th>
              <th class="py-3 px-4 w-24">Sàn</th>
              <th class="py-3 px-4 w-36">Ngành</th>
              <th class="py-3 px-4 w-28">Loại</th>
              <th class="py-3 px-4 w-24 text-center">Trạng thái</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-slate-800/60">
            <tr v-if="isLoading" class="text-center">
              <td colspan="6" class="py-12 text-slate-400">
                <UIcon name="i-heroicons-arrow-path" class="w-8 h-8 animate-spin mx-auto text-emerald-400 mb-2" />
                <p>Đang tải danh sách cổ phiếu...</p>
              </td>
            </tr>

            <tr v-else-if="symbols.length === 0" class="text-center">
              <td colspan="6" class="py-12 text-slate-400">
                <UIcon name="i-heroicons-face-frown" class="w-8 h-8 mx-auto text-slate-600 mb-2" />
                <p>Không tìm thấy mã cổ phiếu nào phù hợp với bộ lọc.</p>
              </td>
            </tr>

            <tr
              v-for="sym in symbols"
              :key="sym.symbol"
              class="hover:bg-slate-800/40 transition-colors group"
            >
              <td class="py-3 px-4 font-mono font-bold text-sm">
                <NuxtLink
                  :to="`/stock/${sym.symbol}`"
                  class="text-emerald-400 hover:text-emerald-300 hover:underline flex items-center gap-1.5"
                >
                  {{ sym.symbol }}
                  <UIcon name="i-heroicons-arrow-up-right" class="w-3.5 h-3.5 opacity-0 group-hover:opacity-100 transition-opacity" />
                </NuxtLink>
              </td>
              <td class="py-3 px-4 font-medium text-slate-200 max-w-xs truncate">
                {{ sym.organ_name || '—' }}
              </td>
              <td class="py-3 px-4">
                <span
                  class="inline-block px-2 py-0.5 rounded text-[11px] font-mono font-semibold"
                  :class="getExchangeBadgeClass(sym.exchange)"
                >
                  {{ sym.exchange || '—' }}
                </span>
              </td>
              <td class="py-3 px-4 text-slate-400 truncate max-w-xs">
                {{ sym.industry || '—' }}
              </td>
              <td class="py-3 px-4 text-slate-400">
                {{ sym.asset_type }}
              </td>
              <td class="py-3 px-4 text-center">
                <span
                  v-if="sym.is_active"
                  class="inline-flex items-center gap-1 text-[11px] text-emerald-400 font-semibold"
                >
                  <UIcon name="i-heroicons-check-circle" class="w-4 h-4" />
                  Giao dịch
                </span>
                <span
                  v-else
                  class="inline-flex items-center gap-1 text-[11px] text-rose-400 font-semibold"
                >
                  <UIcon name="i-heroicons-minus-circle" class="w-4 h-4" />
                  Tạm dừng
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination Footer -->
      <div v-if="total > limit" class="p-4 border-t border-slate-800 flex items-center justify-between">
        <p class="text-xs text-slate-400">
          Hiển thị từ {{ page * limit + 1 }} đến {{ Math.min((page + 1) * limit, total) }} trong tổng số {{ total }}
        </p>

        <div class="flex items-center gap-2">
          <UButton
            color="gray"
            variant="solid"
            size="xs"
            :disabled="page === 0 || isLoading"
            @click="page--; loadSymbols()"
          >
            Trang trước
          </UButton>
          <span class="text-xs font-mono text-slate-300 px-2">
            {{ page + 1 }} / {{ maxPages }}
          </span>
          <UButton
            color="gray"
            variant="solid"
            size="xs"
            :disabled="page >= maxPages - 1 || isLoading"
            @click="page++; loadSymbols()"
          >
            Trang sau
          </UButton>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { StockSymbolItem } from "~/client/stockService"
import { StockService } from "~/client/stockService"

useHead({
  title: "Thị trường cổ phiếu - Vnstock Quants",
})

const { showErrorToast } = useCustomToast()

const search = ref("")
const selectedExchange = ref<string>("ALL")
const page = ref(0)
const limit = 50
const total = ref(0)
const symbols = ref<StockSymbolItem[]>([])
const isLoading = ref(false)

const exchangeOptions = [
  { label: "Tất cả các sàn", value: "ALL" },
  { label: "HOSE (HSX)", value: "HOSE" },
  { label: "HNX", value: "HNX" },
  { label: "UPCOM", value: "UPCOM" },
]

const maxPages = computed(() => Math.ceil(total.value / limit) || 1)

let searchDebounceTimer: NodeJS.Timeout | null = null

const onSearchChange = () => {
  if (searchDebounceTimer) clearTimeout(searchDebounceTimer)
  searchDebounceTimer = setTimeout(() => {
    page.value = 0
    loadSymbols()
  }, 350)
}

const onExchangeChange = () => {
  page.value = 0
  loadSymbols()
}

const getExchangeBadgeClass = (exchange: string | null) => {
  switch (exchange) {
    case "HOSE":
      return "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
    case "HNX":
      return "bg-blue-500/10 text-blue-400 border border-blue-500/20"
    case "UPCOM":
      return "bg-amber-500/10 text-amber-400 border border-amber-500/20"
    default:
      return "bg-slate-800 text-slate-400"
  }
}

const loadSymbols = async () => {
  isLoading.value = true
  try {
    const exchange =
      selectedExchange.value === "ALL" ? undefined : selectedExchange.value
    const res = await StockService.listSymbols({
      query: {
        skip: page.value * limit,
        limit,
        search: search.value.trim() || undefined,
        exchange,
      },
    })
    symbols.value = res.data ?? []
    total.value = res.count ?? 0
  } catch (err: unknown) {
    const error = err as { message?: string }
    showErrorToast(
      "Lỗi tải danh sách cổ phiếu",
      error?.message || "Không thể kết nối đến máy chủ.",
    )
  } finally {
    isLoading.value = false
  }
}

onMounted(() => {
  loadSymbols()
})
</script>

// frontend/src/routes/_layout/stock.tsx
import { useQuery } from "@tanstack/react-query"
import { createFileRoute, Link } from "@tanstack/react-router"
import {
  ArrowDownRight,
  ArrowUpRight,
  BarChart3,
  RefreshCw,
  Search,
} from "lucide-react"
import { useState } from "react"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { type StockSymbolItem, StockService } from "@/client"

export const Route = createFileRoute("/_layout/stock")({
  component: StockMarket,
  head: () => ({
    meta: [
      {
        title: "Stock Market - vnstock",
      },
    ],
  }),
})

function StockMarket() {
  const [search, setSearch] = useState("")
  const [exchange, setExchange] = useState<string | undefined>(undefined)
  const [page, setPage] = useState(0)
  const limit = 50

  const { data, isLoading, refetch } = useQuery({
    queryKey: ["stock-symbols", search, exchange, page],
    queryFn: () =>
      StockService.listSymbols({
        query: {
          skip: page * limit,
          limit,
          search: search || undefined,
          exchange: exchange === "all" ? undefined : exchange,
        },
      }),
    staleTime: 60_000,
  })

  const symbols = data?.data ?? []
  const total = data?.count ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Stock Market</h1>
          <p className="text-muted-foreground">
            Dữ liệu chứng khoán Việt Nam — {total} mã
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          disabled={isLoading}
        >
          <RefreshCw
            className={`mr-2 h-4 w-4 ${isLoading ? "animate-spin" : ""}`}
          />
          Refresh
        </Button>
      </div>

      {/* Filters */}
      <div className="flex gap-4">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Tìm mã CK hoặc tên công ty..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value)
              setPage(0)
            }}
            className="pl-10"
          />
        </div>
        <Select
          value={exchange ?? "all"}
          onValueChange={(v) => {
            setExchange(v === "all" ? undefined : v)
            setPage(0)
          }}
        >
          <SelectTrigger className="w-[160px]">
            <SelectValue placeholder="Sàn" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Tất cả</SelectItem>
            <SelectItem value="HOSE">HOSE</SelectItem>
            <SelectItem value="HNX">HNX</SelectItem>
            <SelectItem value="UPCOM">UPCOM</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Stock Table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="h-5 w-5" />
            Danh sách mã chứng khoán
          </CardTitle>
          <CardDescription>
            Click vào mã CK để xem chi tiết biểu đồ và thông tin công ty
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Mã CK</TableHead>
                <TableHead>Tên công ty</TableHead>
                <TableHead className="w-[80px]">Sàn</TableHead>
                <TableHead className="w-[120px]">Ngành</TableHead>
                <TableHead className="w-[80px]">Loại</TableHead>
                <TableHead className="w-[80px] text-center">
                  Trạng thái
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8">
                    <RefreshCw className="mx-auto h-6 w-6 animate-spin text-muted-foreground" />
                  </TableCell>
                </TableRow>
              ) : symbols.length === 0 ? (
                <TableRow>
                  <TableCell
                    colSpan={6}
                    className="text-center py-8 text-muted-foreground"
                  >
                    Không tìm thấy kết quả
                  </TableCell>
                </TableRow>
              ) : (
                symbols.map((sym: StockSymbolItem) => (
                  <TableRow key={sym.symbol} className="cursor-pointer">
                    <TableCell>
                      <Link
                        to="/stock/$symbol"
                        params={{ symbol: sym.symbol }}
                        className="font-mono font-semibold text-primary hover:underline"
                      >
                        {sym.symbol}
                      </Link>
                    </TableCell>
                    <TableCell className="max-w-[300px] truncate">
                      {sym.organ_name || "—"}
                    </TableCell>
                    <TableCell>
                      <span className="inline-flex items-center rounded-md bg-secondary px-2 py-1 text-xs font-medium">
                        {sym.exchange || "—"}
                      </span>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground truncate max-w-[120px]">
                      {sym.asset_type}
                    </TableCell>
                    <TableCell className="text-sm">
                      {sym.asset_type}
                    </TableCell>
                    <TableCell className="text-center">
                      {sym.is_active ? (
                        <ArrowUpRight className="mx-auto h-4 w-4 text-green-500" />
                      ) : (
                        <ArrowDownRight className="mx-auto h-4 w-4 text-red-500" />
                      )}
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>

          {/* Pagination */}
          {total > limit && (
            <div className="flex items-center justify-between mt-4">
              <p className="text-sm text-muted-foreground">
                Trang {page + 1} / {Math.ceil(total / limit)} ({total} kết quả)
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setPage(Math.max(0, page - 1))}
                  disabled={page === 0}
                >
                  Trước
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    setPage(Math.min(Math.ceil(total / limit) - 1, page + 1))
                  }
                  disabled={page >= Math.ceil(total / limit) - 1}
                >
                  Sau
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
