// frontend/pages/trd/phase-5.vue
<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <div class="flex items-center gap-2 text-xs text-slate-400 font-mono mb-1">
          <NuxtLink to="/" class="hover:text-emerald-400">Dashboard</NuxtLink>
          <span>/</span>
          <span class="text-emerald-400">TRD Phase 5</span>
        </div>
        <h1 class="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
          <UIcon name="i-heroicons-archive-box" class="w-7 h-7 text-rose-400" />
          Phase 5: Sổ nhật ký dự báo (Forecast Journal)
        </h1>
        <p class="text-xs sm:text-sm text-slate-400 mt-1">
          Lưu vết 100% dự báo trước phiên, đối soát kết quả thực tế, chấm điểm MAE/Accuracy và hiệu chuẩn mô hình có kiểm soát.
        </p>
      </div>

      <div class="flex items-center gap-2">
        <span class="px-3 py-1 rounded-full text-xs font-mono font-bold bg-rose-500/10 text-rose-400 border border-rose-500/20 flex items-center gap-1.5">
          <UIcon name="i-heroicons-check-circle" class="w-4 h-4" />
          DoD Journal: 100%
        </span>
      </div>
    </div>

    <!-- Navigation Tabs -->
    <div class="flex border-b border-slate-800 gap-4">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        class="pb-2.5 text-xs font-bold transition-colors border-b-2 flex items-center gap-2"
        :class="activeTab === tab.id ? 'border-rose-400 text-rose-400' : 'border-transparent text-slate-400 hover:text-slate-200'"
        @click="activeTab = tab.id"
      >
        <UIcon :name="tab.icon" class="w-4 h-4" />
        {{ tab.label }}
      </button>
    </div>

    <!-- Tab 1: Spec -->
    <div v-if="activeTab === 'spec'">
      <MarkdownViewer :content="phase5Markdown" filename="trd-phase-5-forecast-journal.md" />
    </div>

    <!-- Tab 2: Test Matrix -->
    <div v-else-if="activeTab === 'tests'">
      <TestMatrix :tests="testCases" />
    </div>

    <!-- Tab 3: Interactive Ledger Simulator -->
    <div v-else-if="activeTab === 'ledger'" class="space-y-6">
      <div class="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-xl space-y-6">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 class="text-base font-bold text-white flex items-center gap-2">
              <UIcon name="i-heroicons-clipboard-document-list" class="w-5 h-5 text-rose-400" />
              Sổ cái Đối soát & Tự học (Forecast Audit Ledger)
            </h3>
            <p class="text-xs text-slate-400">
              Mỗi dự báo được snapshot trước khi phiên diễn ra; tự động chấm điểm khi có kết quả thực tế.
            </p>
          </div>

          <button
            type="button"
            class="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white text-xs font-semibold flex items-center gap-1.5 self-start sm:self-auto transition-colors shadow-lg shadow-rose-600/20"
            @click="resolvePendingForecasts"
          >
            <UIcon name="i-heroicons-arrow-path" class="w-4 h-4" />
            Đối soát kết quả thực tế phiên hôm nay
          </button>
        </div>

        <!-- Ledger Table -->
        <div class="overflow-x-auto rounded-xl border border-slate-800 bg-slate-950/60">
          <table class="w-full text-left text-xs font-mono">
            <thead class="bg-slate-950 text-slate-400 uppercase text-[11px] border-b border-slate-800">
              <tr>
                <th class="py-3 px-4">Mã / Tài sản</th>
                <th class="py-3 px-4">Khung (Horizon)</th>
                <th class="py-3 px-4">Thời điểm dự báo</th>
                <th class="py-3 px-4">Kỳ vọng / Xu hướng</th>
                <th class="py-3 px-4">Thực tế (Actual)</th>
                <th class="py-3 px-4">Sai số (MAE)</th>
                <th class="py-3 px-4 text-center">Trạng thái</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-800/60">
              <tr
                v-for="item in journalEntries"
                :key="item.id"
                class="hover:bg-slate-800/30 transition-colors"
              >
                <td class="py-3 px-4 font-bold text-white">{{ item.symbol }}</td>
                <td class="py-3 px-4">
                  <span class="px-2 py-0.5 rounded text-[10px] bg-slate-800 text-slate-300">
                    {{ item.horizon }}
                  </span>
                </td>
                <td class="py-3 px-4 text-slate-400">{{ item.predictedAt }}</td>
                <td class="py-3 px-4 text-emerald-400 font-bold">
                  {{ item.prediction }}
                </td>
                <td class="py-3 px-4 text-slate-200">
                  {{ item.actual || '— (Đang chờ phiên)' }}
                </td>
                <td class="py-3 px-4 text-slate-300">
                  {{ item.mae !== null ? item.mae.toFixed(1) + ' pts' : '—' }}
                </td>
                <td class="py-3 px-4 text-center">
                  <span
                    class="px-2 py-0.5 rounded text-[10px] font-bold"
                    :class="item.status === 'SCORED' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'"
                  >
                    {{ item.status }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Governed Feedback Loop Explanation -->
        <div class="p-5 rounded-xl bg-slate-950/60 border border-slate-800 space-y-2 text-xs">
          <h4 class="font-bold text-white flex items-center gap-1.5">
            <UIcon name="i-heroicons-arrow-path-rounded-square" class="w-4 h-4 text-rose-400" />
            Cơ chế Tự học có Kiểm soát (Governed Recalibration)
          </h4>
          <p class="text-slate-400 leading-relaxed">
            Hệ thống tính toán Directional Accuracy và Brier Score trên toàn bộ lịch sử sổ nhật ký. Khi tỷ lệ dự đoán vượt ngưỡng kiểm thử Walk-Forward, phiên bản model mới (Model Version Snapshot) được tạo ra. Mọi thay đổi trọng số đều có thể Rollback lập tức về trạng thái an toàn trước đó.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { phase5Markdown } from "~/data/trd/phase5SpecContent"
useHead({
  title: "TRD Phase 5: Forecast Journal - Vnstock Quants",
})

const activeTab = ref<"spec" | "tests" | "ledger">("spec")
const { showSuccessToast } = useCustomToast()

const tabs: Array<{
  id: "spec" | "tests" | "ledger"
  label: string
  icon: string
}> = [
  {
    id: "spec",
    label: "Tài liệu đặc tả (TRD Spec)",
    icon: "i-heroicons-document-text",
  },
  {
    id: "tests",
    label: "Ma trận kiểm thử (Test Matrix)",
    icon: "i-heroicons-check-badge",
  },
  {
    id: "ledger",
    label: "Mô phỏng Sổ cái Audit",
    icon: "i-heroicons-clipboard-document-list",
  },
]

const journalEntries = ref([
  {
    id: 1,
    symbol: "VN30F1M",
    horizon: "ATC_AUCTION",
    predictedAt: "14:15:00",
    prediction: "LONG (1328.5)",
    actual: "1330.2",
    mae: 1.7,
    status: "SCORED",
  },
  {
    id: 2,
    symbol: "VN30F1M",
    horizon: "NEXT_DAY (T+1)",
    predictedAt: "15:30:00 (Hôm qua)",
    prediction: "BULLISH (+12 pts)",
    actual: "+14.5 pts",
    mae: 2.5,
    status: "SCORED",
  },
  {
    id: 3,
    symbol: "VN30F1M",
    horizon: "ATC_AUCTION",
    predictedAt: "14:15:00 (Hôm nay)",
    prediction: "SHORT (1315.0)",
    actual: null,
    mae: null,
    status: "PENDING",
  },
  {
    id: 4,
    symbol: "FPT",
    horizon: "WEEKLY_ALPHA",
    predictedAt: "Đầu tuần",
    prediction: "OUTPERFORM (+5%)",
    actual: null,
    mae: null,
    status: "PENDING",
  },
])

const resolvePendingForecasts = () => {
  journalEntries.value = journalEntries.value.map((item) => {
    if (item.status === "PENDING") {
      return {
        ...item,
        actual: item.symbol === "VN30F1M" ? "1313.8" : "+6.2%",
        mae: item.symbol === "VN30F1M" ? 1.2 : 1.2,
        status: "SCORED",
      }
    }
    return item
  })
  showSuccessToast(
    "Đã đối soát sổ cái!",
    "Các dự báo PENDING đã được backfill dữ liệu thực tế và chấm điểm độ chính xác.",
  )
}

const testCases = [
  {
    id: "TEST-JRN-01",
    group: "Ledger Persistence",
    scenario:
      "Ghi nhận dự báo tại thời điểm T với engine_weights và model_version",
    expectation:
      "Lưu vào database ngay lập tức với status='pending'; không cho phép sửa đổi predicted_at",
    status: "PASS" as const,
  },
  {
    id: "TEST-JRN-02",
    group: "Realization Backfill",
    scenario: "Cập nhật actual_value khi phiên kết thúc",
    expectation:
      "Status chuyển sang 'resolved'; hệ thống lưu audit trail thời gian đối soát",
    status: "PASS" as const,
  },
  {
    id: "TEST-JRN-03",
    group: "Automated Scoring",
    scenario:
      "Tính toán sai số tuyệt đối trung bình (MAE) và độ chính xác hướng đi (Directional Accuracy)",
    expectation: "Tự động tính đúng MAE; chuyển status sang 'scored'",
    status: "PASS" as const,
  },
  {
    id: "TEST-RCAL-01",
    group: "Governed Recalibration",
    scenario: "Hiệu chuẩn trọng số Engine mới trên tập dữ liệu lịch sử",
    expectation:
      "Bắt buộc tạo model_version mới; duy trì snapshot phiên bản cũ cho phép rollback",
    status: "PASS" as const,
  },
]
</script>

// frontend/src/routes/_layout/trd/phase-5.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Check,
  CheckCircle2,
  Copy,
  Cpu,
  Download,
  FileCode,
  History,
  Layers,
  Scale,
  Search,
  ShieldAlert,
  Sparkles,
  Terminal,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { phase5Markdown } from "./-phase5SpecContent";

export const Route = createFileRoute("/_layout/trd/phase-5")({
  component: Phase5TRDPage,
  head: () => ({
    meta: [
      {
        title: "TRD Phase 5: Forecast Journal & Self-Learning - vnstock",
      },
      {
        name: "description",
        content:
          "Technical Requirements Document (TRD), Immutable Forecast Journal Ledger, Brier Score / MAE Automated Scoring & Governed Recalibration Loop for Vnstock.",
      },
    ],
  }),
});

interface TestCase {
  id: string;
  group:
    | "Forecast Ledger & Immutability"
    | "Automated Scoring (Post-Market)"
    | "Recalibration & Anti-Overfit"
    | "Model Versioning & Rollback";
  scenario: string;
  expectation: string;
  status: "READY" | "SPECIFIED";
}

const testCases: TestCase[] = [
  {
    id: "TEST-JOURNAL-01",
    group: "Forecast Ledger & Immutability",
    scenario: "Ensemble sinh tín hiệu Long VN30F1M",
    expectation:
      "Tự động tạo 1 row trong ForecastJournal với status = PENDING, predicted_at lưu chuẩn UTC",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-02",
    group: "Forecast Ledger & Immutability",
    scenario: "Thử cập nhật trường predicted_target_price của một dự báo trong quá khứ",
    expectation:
      "Hệ thống từ chối cập nhật hoặc kiểm toán phát hiện vi phạm tính bất biến",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-03",
    group: "Automated Scoring (Post-Market)",
    scenario: "Chạy bộ chấm điểm ATC: Dự báo Tăng (P=0.8), thực tế giá Tăng",
    expectation:
      "directional_correct = True, brier_score = (0.8 - 1.0)^2 = 0.04 chuẩn xác",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-04",
    group: "Automated Scoring (Post-Market)",
    scenario: "Chạy bộ chấm điểm ATC: Dự báo Tăng (P=0.7), thực tế giá Giảm",
    expectation:
      "directional_correct = False, brier_score = (0.7 - 0.0)^2 = 0.49 chuẩn xác",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-05",
    group: "Automated Scoring (Post-Market)",
    scenario: "Tính toán sai số tuyệt đối MAE cho dự báo giá 1310 khi thực tế là 1305",
    expectation:
      "absolute_error = abs(1310 - 1305) = 5.0 điểm",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-06",
    group: "Recalibration & Anti-Overfit",
    scenario: "Đề xuất trọng số mới tính ra chênh lệch +12% so với trọng số cũ",
    expectation:
      "Thuật toán clip kẹp biên độ dịch chuyển lại ở mức tối đa +5.0%, chống hiện tượng giật cục",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-07",
    group: "Recalibration & Anti-Overfit",
    scenario: "Sinh phiên bản trọng số mới qua thuật toán Softmax 30 ngày",
    expectation:
      "Bản ghi ModelVersionSnapshot được lưu với is_active = False, chưa tác động luồng live",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-08",
    group: "Model Versioning & Rollback",
    scenario: "Admin gọi API POST /promote phiên bản mới",
    expectation:
      "Phiên bản cũ chuyển is_active = False, phiên bản mới chuyển is_active = True an toàn",
    status: "READY",
  },
  {
    id: "TEST-JOURNAL-09",
    group: "Model Versioning & Rollback",
    scenario: "Gọi API POST /rollback về phiên bản v1.0.0 trước đó",
    expectation:
      "Hệ thống đổi cờ is_active tức thì, luồng live nhận lại trọng số cũ trong 1 nốt nhạc",
    status: "READY",
  },
];

const apiEndpoints = [
  {
    method: "GET",
    path: "/api/v1/quant/journal/history",
    desc: "Truy vấn toàn bộ sổ nhật ký dự báo kèm bộ lọc symbol, horizon, status",
    auth: "JWT (CurrentUser)",
  },
  {
    method: "GET",
    path: "/api/v1/quant/journal/metrics",
    desc: "Lấy báo cáo tổng hợp: Directional Accuracy (Winrate), Brier Score 30 ngày",
    auth: "JWT (CurrentUser)",
  },
  {
    method: "GET",
    path: "/api/v1/quant/versions",
    desc: "Xem danh sách các phiên bản mô hình, snapshot tham số và trạng thái active",
    auth: "JWT (CurrentUser)",
  },
  {
    method: "POST",
    path: "/api/v1/quant/versions/{version_tag}/promote",
    desc: "Phê duyệt áp dụng phiên bản trọng số mới vào luồng tính toán thực tế",
    auth: "JWT (Admin)",
  },
  {
    method: "POST",
    path: "/api/v1/quant/versions/{version_tag}/rollback",
    desc: "Khôi phục 1-click về phiên bản tham số trước đó (Rollback an toàn)",
    auth: "JWT (Admin)",
  },
];

export function Phase5TRDPage() {
  const [copied, setCopied] = useState(false);
  const [testSearch, setTestSearch] = useState("");
  const [selectedGroup, setSelectedGroup] = useState<string>("ALL");

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(phase5Markdown);
      setCopied(true);
      toast.success("Đã sao chép nội dung TRD Phase 5 vào clipboard!");
      setTimeout(() => setCopied(false), 2500);
    } catch {
      toast.error("Không thể sao chép vào clipboard");
    }
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([phase5Markdown], {
      type: "text/markdown;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "phase_5_specification.md";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("Đang tải xuống file phase_5_specification.md");
  };

  const filteredTests = testCases.filter((t) => {
    const matchesSearch =
      t.id.toLowerCase().includes(testSearch.toLowerCase()) ||
      t.scenario.toLowerCase().includes(testSearch.toLowerCase()) ||
      t.expectation.toLowerCase().includes(testSearch.toLowerCase());
    const matchesGroup = selectedGroup === "ALL" || t.group === selectedGroup;
    return matchesSearch && matchesGroup;
  });

  return (
    <div className="flex flex-col gap-8 pb-12">
      {/* Header & Breadcrumb */}
      <div className="flex flex-col gap-4 border-b pb-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-muted-foreground">
              DOCUMENTATION
            </Badge>
            <span className="text-muted-foreground">/</span>
            <Badge variant="secondary" className="font-mono text-xs">
              TRD
            </Badge>
            <span className="text-muted-foreground">/</span>
            <Badge variant="default" className="bg-purple-600/90 text-xs">
              PHASE 5
            </Badge>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" asChild className="gap-1.5">
              <Link to="/trd/phase-4">
                <Layers className="h-4 w-4 text-indigo-500" />
                <span>Xem Phase 4</span>
              </Link>
            </Button>
            <Button variant="outline" size="sm" asChild className="gap-1.5">
              <Link to="/trd/phase-6">
                <Cpu className="h-4 w-4 text-cyan-500" />
                <span>Xem Phase 6</span>
              </Link>
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyMarkdown}
              className="gap-1.5"
            >
              {copied ? (
                <Check className="h-4 w-4 text-emerald-500" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              <span>{copied ? "Đã chép" : "Sao chép TRD"}</span>
            </Button>
            <Button
              size="sm"
              onClick={handleDownloadMarkdown}
              className="gap-1.5 bg-purple-600 hover:bg-purple-700 text-white"
            >
              <Download className="h-4 w-4" />
              <span>Tải xuống .MD</span>
            </Button>
          </div>
        </div>

        <div className="flex flex-col gap-2">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-purple-500/10 text-purple-500 border border-purple-500/20">
              <History className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">
                TRD Phase 5: Sổ Nhật Ký Dự Báo & Vòng Lặp Tự Học Có Kiểm Soát
              </h1>
              <p className="text-sm text-muted-foreground">
                Lưu vết 100% tín hiệu, tự động chấm điểm sai số sau phiên và cơ chế đề xuất hiệu chuẩn trọng số engine có kiểm soát (rollback versioning)
              </p>
            </div>
          </div>
        </div>

        {/* Master Rule Reminder Alert */}
        <div className="rounded-lg border border-purple-500/30 bg-purple-500/5 p-4 text-sm">
          <div className="flex items-start gap-3">
            <ShieldAlert className="mt-0.5 h-5 w-5 flex-shrink-0 text-purple-500" />
            <div className="flex flex-col gap-1">
              <span className="font-semibold text-purple-600 dark:text-purple-400">
                Tuân Thủ Master Rule 3: Forecast Auditability & Governed Learning
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Mọi dự báo đều bất biến và lưu tại thời điểm phát sinh (<code>predicted_at</code>), loại bỏ 100% Look-Ahead Bias. Vòng lặp tự học chỉ điều chỉnh <strong>trọng số Ensemble</strong>, tuyệt đối không tự sửa code logic. Cần có sự phê duyệt của con người trước khi áp dụng trọng số mới.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Tabs Layout */}
      <Tabs defaultValue="architecture" className="flex flex-col gap-6">
        <TabsList className="grid w-full grid-cols-2 lg:grid-cols-5 h-auto p-1 bg-muted/60">
          <TabsTrigger value="architecture" className="gap-2 py-2">
            <Layers className="h-4 w-4 text-purple-500" />
            <span>Kiến Trúc 2 Tầng</span>
          </TabsTrigger>
          <TabsTrigger value="scoring" className="gap-2 py-2">
            <Scale className="h-4 w-4 text-amber-500" />
            <span>Công Thức Chấm Điểm</span>
          </TabsTrigger>
          <TabsTrigger value="recalibration" className="gap-2 py-2">
            <Sparkles className="h-4 w-4 text-emerald-500" />
            <span>Hiệu Chuẩn Softmax</span>
          </TabsTrigger>
          <TabsTrigger value="tests" className="gap-2 py-2">
            <CheckCircle2 className="h-4 w-4 text-blue-500" />
            <span>Ma Trận Test ({testCases.length})</span>
          </TabsTrigger>
          <TabsTrigger value="markdown" className="gap-2 py-2">
            <FileCode className="h-4 w-4 text-cyan-500" />
            <span>Tài Liệu Raw MD</span>
          </TabsTrigger>
        </TabsList>

        {/* TAB 1: ARCHITECTURE */}
        <TabsContent value="architecture" className="flex flex-col gap-6 m-0">
          <Card className="border shadow-sm">
            <CardHeader className="border-b bg-muted/20">
              <CardTitle className="text-lg flex items-center gap-2">
                <History className="h-5 w-5 text-purple-500" />
                Kiến Trúc 2 Tầng: Ghi Sổ (Layer A) & Hiệu Chuẩn (Layer B)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="border rounded-lg p-5 bg-muted/10 flex flex-col gap-3">
                  <Badge className="bg-purple-600 text-white w-fit text-xs">TẦNG A: RECORD & MEASURE</Badge>
                  <h4 className="font-semibold text-base">Bắt Buộc & Thường Trực 100%</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Mỗi khi bộ Ensemble sinh tín hiệu, lập tức ghi 1 bản ghi vào bảng <code>ForecastJournal</code> với trạng thái <code>PENDING</code>. Khi phiên kết thúc, worker tự động lấy giá thực tế để tính Directional Accuracy, Brier Score và MAE.
                  </p>
                </div>

                <div className="border rounded-lg p-5 bg-purple-500/5 border-purple-500/30 flex flex-col gap-3">
                  <Badge className="bg-indigo-600 text-white w-fit text-xs">TẦNG B: GOVERNED RECALIBRATION</Badge>
                  <h4 className="font-semibold text-base">Có Kiểm Soát & Khôi Phục Được</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Dựa trên hiệu năng lăn 30 ngày, thuật toán tự động tính toán trọng số tối ưu mới $w_1, w_2, w_3$. Rào chắn kẹp biên độ dịch chuyển &le; 5% giúp chống hiện tượng Overfitting. Cần Admin bấm duyệt hoặc bấm Rollback khôi phục trong 1 giây.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* TAB 2: SCORING FORMULAS */}
        <TabsContent value="scoring" className="flex flex-col gap-6 m-0">
          <Card className="border shadow-sm">
            <CardHeader className="border-b bg-muted/20">
              <CardTitle className="text-lg flex items-center gap-2">
                <Scale className="h-5 w-5 text-amber-500" />
                Công Thức Toán Học Chấm Điểm Sai Số Sau Phiên
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 flex flex-col gap-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="border rounded-lg p-4 bg-muted/10">
                  <h4 className="font-semibold text-sm mb-1">Directional Accuracy (DA)</h4>
                  <p className="text-xs text-muted-foreground">Tỷ lệ % dự đoán đúng hướng tăng / giảm của thị trường:</p>
                  <pre className="p-2 bg-muted rounded font-mono text-xs mt-2 text-emerald-600">
                    DA = Sum(sign(y_hat) == sign(y)) / N
                  </pre>
                </div>

                <div className="border rounded-lg p-4 bg-muted/10">
                  <h4 className="font-semibold text-sm mb-1">Brier Score (Xác Suất)</h4>
                  <p className="text-xs text-muted-foreground">Độ lệch bình phương xác suất so với kết quả thực tế (0 hoặc 1):</p>
                  <pre className="p-2 bg-muted rounded font-mono text-xs mt-2 text-amber-600">
                    BS = Sum((p_i - o_i)^2) / N
                  </pre>
                  <p className="text-[11px] text-muted-foreground mt-1">Càng gần 0.0 càng hoàn hảo (&lt; 0.25 là có ý nghĩa thống kê).</p>
                </div>

                <div className="border rounded-lg p-4 bg-muted/10">
                  <h4 className="font-semibold text-sm mb-1">Sai Số Giá (MAE / RMSE)</h4>
                  <p className="text-xs text-muted-foreground">Độ lệch tuyệt đối giữa mức giá mục tiêu và giá khớp ATC thực tế:</p>
                  <pre className="p-2 bg-muted rounded font-mono text-xs mt-2 text-purple-600">
                    MAE = Sum(|P_pred - P_actual|) / N
                  </pre>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* TAB 3: RECALIBRATION */}
        <TabsContent value="recalibration" className="flex flex-col gap-6 m-0">
          <Card className="border shadow-sm">
            <CardHeader className="border-b bg-muted/20">
              <CardTitle className="text-lg flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-emerald-500" />
                Thuật Toán Softmax Hiệu Chuẩn Trọng Số Engine
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 flex flex-col gap-4">
              <div className="border rounded-lg p-4 bg-muted/10 flex flex-col gap-2">
                <span className="font-semibold text-sm">Điểm hiệu năng tổng hợp Sk và Softmax Rebalancing:</span>
                <pre className="p-3 bg-muted rounded font-mono text-xs overflow-x-auto text-emerald-600">
                  S_k = alpha * DA_k + (1 - alpha) * (1 - BS_k)
                  w_k* = exp(S_k / tau) / Sum(exp(S_j / tau))
                </pre>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="border rounded-lg p-4 bg-muted/10">
                  <h4 className="font-semibold text-sm mb-1">Giới hạn dịch chuyển (Max Weight Shift)</h4>
                  <p className="text-xs text-muted-foreground">
                    Trọng số không được thay đổi quá <strong>&plusmn; 5.0%</strong> trong một chu kỳ hiệu chuẩn, ngăn chặn hiện tượng Overfitting trên chuỗi ngày nhiễu ngẫu nhiên.
                  </p>
                </div>
                <div className="border rounded-lg p-4 bg-muted/10">
                  <h4 className="font-semibold text-sm mb-1">Ngưỡng biên an toàn (Weight Bounds)</h4>
                  <p className="text-xs text-muted-foreground">
                    Mọi trọng số đều nằm trong khoảng <strong>[0.15, 0.60]</strong>, đảm bảo không triệt tiêu bất kỳ Engine phân tích nào về 0.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* API Endpoints */}
          <Card className="border shadow-sm">
            <CardHeader className="border-b bg-muted/20">
              <CardTitle className="text-lg flex items-center gap-2">
                <Terminal className="h-5 w-5 text-purple-500" />
                Danh Sách API Endpoints Quản Trị & Rollback
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-24">Method</TableHead>
                    <TableHead className="w-80">Path</TableHead>
                    <TableHead>Mô tả chức năng</TableHead>
                    <TableHead className="w-36">Quyền truy cập</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {apiEndpoints.map((ep) => (
                    <TableRow key={ep.path}>
                      <TableCell>
                        <Badge variant={ep.method === "GET" ? "secondary" : "default"}>
                          {ep.method}
                        </Badge>
                      </TableCell>
                      <TableCell className="font-mono text-xs">{ep.path}</TableCell>
                      <TableCell className="text-xs text-muted-foreground">{ep.desc}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="text-xs">{ep.auth}</Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* TAB 4: TEST MATRIX */}
        <TabsContent value="tests" className="flex flex-col gap-6 m-0">
          <Card className="border shadow-sm">
            <CardHeader className="border-b bg-muted/20">
              <CardTitle className="text-lg flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5 text-blue-500" />
                Ma Trận Kịch Bản Kiểm Thử (Test Acceptance Matrix)
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6 flex flex-col gap-4">
              <div className="flex flex-wrap items-center gap-4">
                <div className="relative flex-1 min-w-[240px]">
                  <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Tìm kiếm kịch bản test hoặc mã test..."
                    value={testSearch}
                    onChange={(e) => setTestSearch(e.target.value)}
                    className="pl-8"
                  />
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    variant={selectedGroup === "ALL" ? "default" : "outline"}
                    size="sm"
                    onClick={() => setSelectedGroup("ALL")}
                  >
                    Tất cả ({testCases.length})
                  </Button>
                </div>
              </div>

              <div className="border rounded-md overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-36">Mã Test</TableHead>
                      <TableHead className="w-56">Phân nhóm</TableHead>
                      <TableHead>Kịch bản thử nghiệm</TableHead>
                      <TableHead>Kết quả kỳ vọng</TableHead>
                      <TableHead className="w-24 text-right">Trạng thái</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredTests.map((tc) => (
                      <TableRow key={tc.id}>
                        <TableCell className="font-mono text-xs font-semibold">{tc.id}</TableCell>
                        <TableCell className="text-xs text-muted-foreground">{tc.group}</TableCell>
                        <TableCell className="text-xs font-medium">{tc.scenario}</TableCell>
                        <TableCell className="text-xs text-muted-foreground">{tc.expectation}</TableCell>
                        <TableCell className="text-right">
                          <Badge className="bg-emerald-500/10 text-emerald-600 border-emerald-500/30 text-[10px]">
                            {tc.status}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* TAB 5: MARKDOWN RAW */}
        <TabsContent value="markdown" className="flex flex-col gap-4 m-0">
          <div className="flex items-center justify-between">
            <span className="text-sm text-muted-foreground">
              Toàn văn tài liệu đặc tả kỹ thuật phase_5_specification.md
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyMarkdown}
              className="gap-1.5"
            >
              {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
              <span>{copied ? "Đã chép" : "Sao chép Markdown"}</span>
            </Button>
          </div>
          <pre className="p-4 bg-muted/40 border rounded-lg font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[700px] overflow-y-auto">
            {phase5Markdown}
          </pre>
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default Phase5TRDPage;
